version: '3.8'

services:
  hub-helper:
    build: .
    ports:
      - "5414:5414"
    volumes:
      # Mount your projects directory - CHANGE THIS PATH TO YOUR PROJECTS FOLDER
      - /home/toto:/projects
      # Mount Docker socket to allow Docker operations from within container
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount Docker binary (if needed)
      - /usr/bin/docker:/usr/bin/docker:ro
      # Mount data directory for persistent login storage
      - hub-helper-data:/app/data
    environment:
      - PROJECTS_PATH=/projects
      - SECRET_KEY=your-super-secret-key-change-this
      # GitHub OAuth App credentials (optional - get from GitHub Developer Settings)
      - GITHUB_CLIENT_ID=your-github-client-id
      - GITHUB_CLIENT_SECRET=your-github-client-secret
    restart: unless-stopped
    networks:
      - hub-helper-network

networks:
  hub-helper-network:
    driver: bridge

volumes:
  hub-helper-data:
    driver: local
